### ISSUE TITLE
Range FFT result 

### ISSUE THREAD

**Issue by enting8696** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#1]
hi, RAMP-CNN is a great method, thanks for open source.

I would like to ask in the section of [3D Slicing of Range-Velocity-Angle Data](https://github.com/xiangyu-gao/radar-multiple-perspective-object-detection#3d-slicing-of-range-velocity-angle-data), 
you said that For convenience and use the [Range FFT](https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification) result as input and perform the Velocity and Angle FFT during the process of slicing, as these data are input 

2019_04_30_pbms002_000000.mat ~ 2019_04_30_pbms002_000009.mat 

Is the output from file [generate_ra_3dfft.m](https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification/blob/main/generate_ra_3dfft.m) line 69 - 107 ?

And the last question is Why is it divided into two parts, because in the [github](https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification) you provided, after range, velocity, and angle FFT, slice can also generate heatmap, why in this project only use the FFT output of range, and then use slice3d.py Generate angles and velocities? because heatmap and output of slice3d.py is the same right?

Hope you can give me some hint or advice, thanks

**Comment by Xiangyu-Gao** [comment]
Thanks for your questions. The range fft results are not from the generate_ra_3dfft.m script. The reason why I use that is just some personal issues, i.e., I forgot to save the raw data and there is no need to divide into two processing steps. I am sorry for making you confused.
I may update this repo by uploading the raw data and adding the range fft processing in the 3d_slice.py.

**Comment by enting8696** [comment]
Thank you for your efficient reply and also solved my problem !
