### ISSUE TITLE
How to arrange the folder data and template_files used in tran_dop.py and prepare_data.py ?

### ISSUE THREAD

**Issue by Tipper-sun** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#11]
i have downloaded the dataset mentioned in readme, but i don't know how to use. 
please.

**Comment by Xiangyu-Gao** [comment]
You can decompress the downloaded files and relocate them as the following directory manners:

'./template_files/slice_sample_data'
'./template_files/train_test_data'
'./results/C3D-20200904-001923'

**Comment by Tipper-sun** [comment]
Thank you for your reply!
But  I'd rather know the exact form of the data in each folder mentioned above.
please.

**Comment by Xiangyu-Gao** [comment]
For example, the data structure for the first folder would be, which is the same if you decompress the download data directly.
-- './template_files/slice_sample_data'
    -- 2019_04_30

Same for the other two folders
