### ISSUE TITLE
Question about the training labels

### ISSUE THREAD

**Issue by SlytherinGe** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#12]
I find that the training data is literally from your another repo [UWCR](https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection). But the annotation in the release dataset doesn't match the template_files you provided in this repo. How can I transfer the raw annotation into the annotation in this repo?

**Comment by Xiangyu-Gao** [comment]
Hi. For your question about annotation conversion, I have made a function called "convert_annotations.py" and added that to my RAMP-CNN github repository.
I hope that helps.
