### ISSUE TITLE
How to Convert UWCR dataset to the dataset given in The RAMP-CNN paper

### ISSUE THREAD

**Issue by PalgunaGopireddy** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#14]
Table 2 of the RAMP-CNN paper, this code belongs to, it is shown the sizes and frames of the dataset used for RAMP-CNN.
![Capture](https://github.com/Xiangyu-Gao/Radar-multiple-perspective-object-detection/assets/106730853/4ebb46ce-b492-4c21-926a-14d7ce0ea286)

I see you have given the Raw [UWCR dataset](https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection) dataset, but the program code presented here is shown with a sample dataset, to understand it. Even I don't understand that the [UWCR dataset](https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection) data given has 898 * 20+897 * 2 = `19754` frames. But you have shown in table II, that the test dataset itself has `25098` frames.
So, would you please tell how the dataset is created, as shown in Table II of the paper?

**Comment by Xiangyu-Gao** [comment]
Sure. The provided [UWCR dataset](https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection) is just a portion of the complete dataset we collected and used in the RAMP-CNN paper. Therefore, the number of 19754 frames does not match the number in the paper.

**Comment by PalgunaGopireddy** [comment]
Thanks. What about this reply [this reply](https://github.com/Xiangyu-Gao/Radar-multiple-perspective-object-detection/issues/5#issuecomment-1299104466) you have provided?. Does this [CRUW Dataset](https://www.cruwdataset.org/download) is same as [UWCR dataset](https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection) or it has full dataset?

**Comment by Xiangyu-Gao** [comment]
[CRUW Dataset](https://www.cruwdataset.org/download) is also partial and only provides the processed range-angle radar images & camera images
