### ISSUE TITLE
Raw adc data 4D to 3D conversion

### ISSUE THREAD

**Issue by AadeshL** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#18]
How to convert the Raw adc data from 4D (128x4x255x2) to 3D(128x8x255) in order to provide it as an input to slide3d.py

**Comment by Xiangyu-Gao** [comment]
split 128x4x255x2 into 128x4x255x1, and 128x4x255x1, then make concatenation at the second dimension and squeeze the last dimension, you get 128x8x255
