### ISSUE TITLE
In the evaluateion results, only pedestrian AP and AR

### ISSUE THREAD

**Issue by haomingHu-dd** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#19]
Hello！

I follow the prompt of Readme.md, Run the code in the following sequence: python slice3d.py -> python prepare_data.py -m train -dd './data/' ->python prepare_data.py -m test -dd './data/' -> python train_dop.py -m C3D -> python test.py -m C3D -md C3D-20200904-001923 -> python evaluate.py -md C3D-20200904-001923

In the end, there is only the indicator of pedestrians

RAMPCNN) dell@dell-Precision-7920-Tower:/media/dell/data1/radar_dl/Radar-multiple-perspective-object-detection$ python evaluate.py -md C3D-20200904-001923 -rd ./results/
true seq
./results/C3D-20200904-001923/2019_05_28_pm2s012/rod_res.txt
pedestrian: 1913 dets, 1792 gts
 Average Precision  (AP) @[ OLS=0.50:0.90 ] = 0.9126
 Average Recall     (AR) @[ OLS=0.50:0.90 ] = 0.9653
pedestrian: 1913 dets, 1792 gts
 Average Precision  (AP) @[ OLS=0.50:0.90 ] = 0.9126
 Average Precision  (AP) @[ OLS=0.50      ] = 0.9713
 Average Precision  (AP) @[ OLS=0.60      ] = 0.9713
 Average Precision  (AP) @[ OLS=0.70      ] = 0.9489
 Average Precision  (AP) @[ OLS=0.80      ] = 0.9062
 Average Precision  (AP) @[ OLS=0.90      ] = 0.7054
 Average Recall     (AR) @[ OLS=0.50:0.90 ] = 0.9653
 Average Recall     (AR) @[ OLS=0.50      ] = 0.9994
 Average Recall     (AR) @[ OLS=0.75      ] = 0.9821
pedestrian: 1913 dets, 1792 gts
 Average Precision  (AP) @[ OLS=0.50:0.90 ] = 0.9126
 Average Precision  (AP) @[ OLS=0.50      ] = 0.9713
 Average Precision  (AP) @[ OLS=0.60      ] = 0.9713
 Average Precision  (AP) @[ OLS=0.70      ] = 0.9489
 Average Precision  (AP) @[ OLS=0.80      ] = 0.9062
 Average Precision  (AP) @[ OLS=0.90      ] = 0.7054
 Average Recall     (AR) @[ OLS=0.50:0.90 ] = 0.9653
 Average Recall     (AR) @[ OLS=0.50      ] = 0.9994
 Average Recall     (AR) @[ OLS=0.75      ] = 0.9821

What is the problem caused by what is the problem？

**Comment by Xiangyu-Gao** [comment]
This is because, in the sample test set, there is only one file that contains pedestrian objects exclusively and the indications for other classes are skipped. To solve this issue, I would suggest you download more data from the [dataset](https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection) and append the test set in [`evaluate.py`](https://github.com/Xiangyu-Gao/Radar-multiple-perspective-object-detection/blob/main/evaluate.py#L397)
