### ISSUE TITLE
Error in training due to inconsistent dataloading

### ISSUE THREAD

**Issue by E-Olcay** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#20]
I have run the train script as described in the READme.md and I am getting a "value error" because the lenght of the list 'obj_info' is not consistent in all the iterations. Please find attached a few snippets from multiple runs for more understanding.

![image](https://github.com/Xiangyu-Gao/Radar-multiple-perspective-object-detection/assets/65757805/a8666190-6a6f-4d12-8f42-53f63d6cfca3)

![image](https://github.com/Xiangyu-Gao/Radar-multiple-perspective-object-detection/assets/65757805/f46ed298-ce0a-4a50-82c0-1acb99ebab07)

![image](https://github.com/Xiangyu-Gao/Radar-multiple-perspective-object-detection/assets/65757805/1200142f-27fb-4e1f-83a1-1b1204047f09)

![image](https://github.com/Xiangyu-Gao/Radar-multiple-perspective-object-detection/assets/65757805/15598b0b-6aa0-4030-9d56-c992344698c1)

**Comment by Xiangyu-Gao** [comment]
I believe this is a dataLoader issue similar to this [thread](https://github.com/Xiangyu-Gao/Radar-multiple-perspective-object-detection/issues/2#issuecomment-1741225340), which can be fixed by using the suggested pytorch version.

**Comment by E-Olcay** [comment]
Thanks for the answer. I tried many different things, including setting up an identical virtual environment, different pytorch versions like 1.xx. However, I'm facing the same issue with the shape, except with a batch size of 1.
