### ISSUE TITLE
我在评估中，遇到了AP非常低的问题。

### ISSUE THREAD

**Issue by xiaohuqaq123** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#21]
我完全按照您的库安装，例如torch=1.5.1，python=3.6，AP在0.06~0.1之间，这可能是什么原因导致的？

**Comment by xiaohuqaq123** [comment]
是否因为我训练集只用了您提供的示例数据集？您的C3D-20200904-001923模型是否用了更多的数据集训练生成的

**Comment by Xiangyu-Gao** [comment]
对的 我提供的示例数据只是展示code可以complile和run。 我提供的模型用了大量的数据train出来的。
更多数据可以在这找到  https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection

**Comment by xiaohuqaq123** [comment]
感谢您的回复，我还有另一个问题，劳烦您再看一下。 目前我已经将数据集转换为128 8 255的形式以供slice3d输入，slice3d运行没有报错，但是我找不到RA、VA、RV NPY保存到哪里了。

**Comment by xiaohuqaq123** [comment]
![image](https://github.com/Xiangyu-Gao/Radar-multiple-perspective-object-detection/assets/147484685/d5b18a2c-e3f0-449c-a004-9a4084bae977)
如图所示，我用的是2019_05_09_pbms004这一数据，显示Process finished with exit code 0，但找不到处理后的文件在哪

**Comment by Xiangyu-Gao** [comment]
你可以看一下 save .npy 那一步的path设置在哪？
