### ISSUE TITLE
关于分类结果和目标的对应

### ISSUE THREAD

**Issue by upokey** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#24]
您好，请问在程序中的哪个部分实现了将分类结果对应到目标上，类似这张图

![image](https://github.com/Xiangyu-Gao/Radar-multiple-perspective-object-detection/assets/145635481/cc836dcf-5fc9-4a07-be45-7a61245547cb)

**Comment by Xiangyu-Gao** [comment]
你好 这段代码没有包含在现在的代码库里
