### ISSUE TITLE
Point cloud and projection map generation

### ISSUE THREAD

**Issue by Srivatsa1648** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#27]
How to generate point cloud and projection map from the given data? Pls reply asap I have a project to complete

**Comment by Xiangyu-Gao** [comment]
see https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification/issues/17#issuecomment-2292868885

**Comment by Srivatsa1648** [comment]
Thank you
