### ISSUE TITLE
How to process the raw .bin data obtained by the radar to get the data in the format of "the raw ADC data now slice_sample_data"?

### ISSUE THREAD

**Issue by Linda0111** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#3]
I want to make my own dataset.The data obtained from the radar is in the format [numRx,numSample*numChirp], what should I do to convert it into the data format input [128,8,255] required in slice_3d.py?
The input data for slice3d.py script has been changed to the raw ADC data now slice_sample_data.

**Comment by Xiangyu-Gao** [comment]
just convert your format [numRx,numSample*numChirp] to [numSample, numRx, numChirp]

**Comment by Linda0111** [comment]
Thank you a lot ! I will try it.
