### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by sutiankang** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#5]
I can not get your test results because I found your dataset only has one picture. Can you tell me how to get fully dataset?
![image](https://user-images.githubusercontent.com/61399929/184624907-377d4bf0-f592-4f75-9cf9-6f83cf956935.png)

**Comment by Xiangyu-Gao** [comment]
Just saw this issue. Sorry for the late reply. I fixed this bug and pushed the new-version code. For more camera images, you can check the website https://www.cruwdataset.org/download
