### ISSUE TITLE
Seems some file missed

### ISSUE THREAD

**Issue by RouChan** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#6]
Hi there. Thanks for your brilliant work and for your generosity to make this repository open source. I successfully trained my model. But when I try to test, seems some files missing.
![Screenshot 2022-11-01 at 16 38 44](https://user-images.githubusercontent.com/55694771/199193480-c629adcf-d104-4ab2-a1b2-6f262c973eae.png)

**Comment by RouChan** [comment]
And for those under Pytorch1.5.1, you may need to add a line of code as follows at the beginning of `train.py`.
```
torch.backends.cudnn.enabled = False
```

**Comment by Xiangyu-Gao** [comment]
Hi Rouchan, thanks for reporting the bug. I fixed it and pushed the new-version code. Please take a look and let me know if doesn't work.

**Comment by RouChan** [comment]
The code goes well now.
Thanks so much.
