### ISSUE TITLE
Seems some models are not available

### ISSUE THREAD

**Issue by RouChan** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#7]
Thanks again for make this brilliant project open source. 

I noticed that in `train_dop.py` file, other model types are available. But when I tried to use it, seems does not work. I do not know whether they are available or not. 
![Screenshot 2022-11-04 at 17 17 28](https://user-images.githubusercontent.com/55694771/199937420-25c856f6-c04f-41f3-916e-e7db41c772ad.png)

**Comment by Xiangyu-Gao** [comment]
Those models are not available now. The issues should be from the dataLoader/data loading process since the C3D model uses 3 data (RA, RV, and VA image) as input while the HG only uses the RA image. You can fix it by working on that.
