### ISSUE TITLE
cuda out of memory 

### ISSUE THREAD

**Issue by siddupp** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#8]
I am getting RuntimeError: CUDA out of memory 
![image](https://user-images.githubusercontent.com/59868895/202836938-28edf759-d201-4fc0-b0cc-fd6bc62cb0df.png)
so can you please share the trained model so i can use directly to test this . thank you

**Comment by Xiangyu-Gao** [comment]
Sorry just saw this request. The trained model was actually shared in google drive. You can access it with the link posted in the documentation.

**Comment by siddupp** [comment]
Thank you for your response

**Comment by PalgunaGopireddy** [comment]
Hi, @Xiangyu-Gao. I also got the same error.

Where can I find the  trained model.  I saw `https://drive.google.com/drive/folders/1TGW6BHi5EZsSCtTsJuwYIQVaIWjl8CLY`. But no trained model is there only dataset is there. Could you tell me, where can I get that.

**Comment by Xiangyu-Gao** [comment]
There is the trained model named C3D-20200904-001923 in this link.

**Comment by siddupp** [comment]
Thanks, I'll check it out.
